INSERT INTO `category` (`id`, `id_group`, `name_pl`, `name_en`, `name_de`) VALUES
(1, 1, 'Dania główne', 'Main courses', ''),
(2, 1, 'Sałatki', 'Salads', ''),
(3, 1, 'Zupy', 'Soups', ''),
(4, 1, 'Desery', 'Desserts', ''),
(5, 1, 'Ciasta i ciastka', 'Cakes and cookies', ''),
(6, 1, 'Dodatki do dań', 'Additions', ''),
(7, 1, 'Przekąski', 'Snacks', ''),
(8, 1, 'Makarony', 'Pastas', ''),
(9, 1, 'Dania mączne', 'Flour dishes', ''),
(10, 1, 'Pasty', 'Pastes', ''),
(11, 1, 'Przetwory', 'Preserves', ''),
(12, 1, 'Drinki', 'Drinks', ''),
(13, 1, 'Ryż i kasze', 'Rice and cereals', ''),
(14, 1, 'Ryby i owoce morza', 'Fish and seafood', ''),
(15, 1, 'Pizza', 'Pizza', ''),
(16, 1, 'Zapiekanki', 'Casseroles', ''),
(18, 1, 'Pierogi', 'Dumplings', ''),
(19, 2, 'Dania mięsne', 'Meat dishes', ''),
(20, 2, 'Ryby i owoce morza', 'Fish and seafood', ''),
(21, 2, 'Dania mączne', 'Flour dishes', ''),
(22, 2, 'Nabiał', 'Dairy', ''),
(23, 2, 'Warzywa', 'Vegetables', ''),
(24, 2, 'Owoce', 'Fruits', ''),
(25, 2, 'Alkohol', 'Alcohol', ''),
(26, 2, 'Ziemniaki', 'Potatoes', ''),
(27, 2, 'Ryż i kasze', 'Rice and cereals', ''),
(28, 2, 'Grzyby', 'Mushrooms', ''),
(29, 3, 'Dania wegetariańskie', 'Vegetarian dishes', ''),
(30, 3, 'Dania bezglutenowe', 'Gluten-free dishes', ''),
(31, 3, 'Dania niskokaloryczne', 'Low calorie dishes', ''),
(32, 3, 'Dania niskocholesterolowe', 'Cholesterol-lowering dishes', ''),
(33, 3, 'Dania wegańskie', 'Vegan dishes', ''),
(34, 3, 'Dania bezbiałkowe', 'Protein-free dishes', ''),
(35, 3, 'Dania bogatobiałkowe', 'Protein dishes', ''),
(36, 1, 'Dla dzieci', 'For kids', ''),
(37, 4, 'Śniadanie', 'Breakfast', ''),
(38, 4, 'Lunch', 'Lunch', ''),
(39, 4, 'Obiad', 'Dinner', ''),
(40, 4, 'Podwieczorek', 'Afternoon snack', ''),
(41, 4, 'Kolacja', 'Supper', ''),
(42, 1, 'Grill', 'Grill', ''),
(43, 5, 'Kuchnia afrykańska', 'African cuisine', ''),
(44, 5, 'Kuchnia angielska', 'English cuisine', ''),
(45, 5, 'Kuchnia polska', 'Polish cuisine', ''),
(46, 5, 'Kuchnia irlandzka', 'Irish cuisine', ''),
(47, 5, 'Kuchnia arabska', 'Arabic cuisine', ''),
(48, 5, 'Kuchnia australijska', 'Australian cuisine', ''),
(49, 5, 'Kuchnia austriacka', 'Austrian cuisine', ''),
(50, 5, 'Kuchnia szwajcarska', 'Swiss cuisine', ''),
(51, 5, 'Kuchnia bałkańska', 'Balkan cuisine', ''),
(52, 5, 'Kuchnia chińska', 'Chineese cuisine', ''),
(53, 5, 'Kuchnia czeska', 'Czech cuisine', ''),
(54, 5, 'Kuchnia francuska', 'French cuisine', ''),
(56, 5, 'Kuchnia grecka', 'Greek cuisine', ''),
(57, 5, 'Kuchnia hiszpańska', 'Spanish cuisine', ''),
(58, 5, 'Kuchnia indyjska', 'Indian cuisine', ''),
(59, 5, 'Kuchnia japońska', 'Japaneese cuisine', ''),
(60, 5, 'Kuchnia meksykańska', 'Mexican cuisine', ''),
(61, 5, 'Kuchnia niemiecka', 'German cuisine', ''),
(62, 5, 'Kuchnia żydowska', 'Jewish cuisine', ''),
(63, 5, 'Kuchnia amerykańska', 'American cuisine', ''),
(64, 5, 'Kuchnia rosyjska', 'Russian cuisine', ''),
(65, 5, 'Kuchnia skandynawska', 'Scandinavian cuisine', ''),
(66, 5, 'Kuchnia tajska', 'Thai cuisine', ''),
(67, 5, 'Kuchnia turecka', 'Turkish cuisine', ''),
(68, 5, 'Kuchnia wietnamska', 'Vietnamese cuisine', ''),
(69, 5, 'Kuchnia włoska', 'Italian cuisine', ''),
(70, 5, 'Kuchnia węgierska', 'Hungarian cuisine', ''),
(71, 6, 'Wiosna', 'Spring', ''),
(72, 6, 'Lato', 'Summer', ''),
(73, 6, 'Jesień', 'Autumn', ''),
(74, 6, 'Zima', 'Winter', '');