INSERT INTO `country` (`pl` ,`en`, `de`) VALUES
('Afganistan' , 'Afghanistan' , 'Afghanistan'),
('Albania' , 'Albania' , 'Albanien'),
('Algieria' , 'Algeria' , 'Algerien'),
('Andora' , 'Andorra' , 'Andorra'),
('Angola' , 'Angola' , 'Angola'),
('Antigua i Barbuda' , 'Antigua and Barbuda' , 'Antigua und Barbuda'),
('Arabia Saudyjska' , 'Saudi Arabia' , 'Saudi-Arabien'),
('Argentyna' , 'Argentina' , 'Argentinien'),
('Armenia' , 'Armenia' , 'Armenien'),
('Australia' , 'Australia' , 'Australien'),
('Austria' , 'Austria' , 'Österreich'),
('Azerbejdżan' , 'Azerbaijan' , 'Aserbaidschan'),
('Bahamy' , 'Bahamas' , 'Bahamas'),
('Bahrajn' , 'Bahrain' , 'Bahrain'),
('Bangladesz' , 'Bangladesh' , 'Bangladesch'),
('Barbados' , 'Barbados' , 'Barbados'),
('Belgia' , 'Belgium' , 'Belgien'),
('Belize' , 'Belize' , 'Belize'),
('Benin' , 'Benin' , 'Benin'),
('Bhutan' , 'Bhutan' , 'Bhutan'),
('Białoruś' , 'Belarus' , 'Weißrussland / Belarus'),
('Birma' , 'Myanmar' , 'Birma'),
('Boliwia' , 'Bolivia' , 'Bolivien'),
('Bośnia i Hercegowina' , 'Bosnia and Herzegovina' , 'Bosnien und Herzegowina'),
('Botswana' , 'Botswana' , 'Botsuana'),
('Brazylia' , 'Brazil' , 'Brasilien'),
('Brunei' , 'Brunei Darussalam' , 'Brunei'),
('Bułgaria' , 'Bulgaria' , 'Bulgarien'),
('Burkina Faso' , 'Burkina Faso' , 'Burkina Faso'),
('Burundi' , 'Burundi' , 'Burundi'),
('Chile' , 'Chile' , 'Chile'),
('Chiny' , 'China' , 'Republik China'),
('Chorwacja' , 'Croatia' , 'Kroatien'),
('Cypr' , 'Cyprus' , 'Zypern'),
('Czad' , 'Chad' , 'Tschad'),
('Czarnogóra' , 'Montenegro' , 'Montenegro'),
('Czechy' , 'Czech Republic' , 'Tschechien'),
('Dania' , 'Denmark' , 'Dänemark'),
('Demokratyczna Republika Konga' , 'Congo' , 'Kongo, Republik'),
('Dominika' , 'Dominica' , 'Dominica'),
('Dominikana' , 'Dominican Republic' , 'Dominikanische Republik'),
('Dżibuti' , 'Djibouti' , 'Dschibuti'),
('Egipt' , 'Egypt' , 'Ägypten'),
('Ekwador' , 'Ecuador' , 'Ecuador'),
('Erytrea' , 'Eritrea' , 'Eritrea'),
('Estonia' , 'Estonia' , 'Estland'),
('Etiopia' , 'Ethiopia' , 'Äthiopien'),
('Fidżi' , 'Fiji' , 'Fidschi'),
('Filipiny' , 'Philippines' , 'Philippinen'),
('Finlandia' , 'Finland' , 'Finnland'),
('Francja' , 'France' , 'Frankreich'),
('Gabon' , 'Gabon' , 'Gabun'),
('Gambia' , 'Gambia' , 'Gambia'),
('Ghana' , 'Ghana' , 'Ghana'),
('Grecja' , 'Greece' , 'Griechenland'),
('Grenada' , 'Grenada' , 'Grenada'),
('Gruzja' , 'Georgia' , 'Georgien'),
('Gujana' , 'Guyana' , 'Guyana'),
('Gwatemala' , 'Guatemala' , 'Guatemala'),
('Gwinea' , 'Guinea' , 'Guinea'),
('Gwinea Bissau' , 'Guinea-Bissau' , 'Guinea-Bissau'),
('Gwinea Równikowa' , 'Equatorial Guinea' , 'Äquatorialguinea'),
('Haiti' , 'Haiti' , 'Haiti'),
('Hiszpania' , 'Spain' , 'Spanien'),
('Holandia' , 'Netherlands' , 'Königreich der Niederlande'),
('Honduras' , 'Honduras' , 'Honduras'),
('Indie' , 'India' , 'Indien'),
('Indonezja' , 'Indonesia' , 'Indonesien'),
('Irak' , 'Iraq' , 'Irak'),
('Iran' , 'Iran' , 'Iran'),
('Irlandia' , 'Ireland' , 'Irland'),
('Islandia' , 'Isle of Man' , 'Island'),
('Izrael' , 'Israel' , 'Israel'),
('Jamajka' , 'Jamaica' , 'Jamaika'),
('Japonia' , 'Japan' , 'Japan'),
('Jemen' , 'Yemen' , 'Jemen'),
('Jordania' , 'Jordan' , 'Jordanien'),
('Kambodża' , 'Cambodia' , 'Kambodscha'),
('Kamerun' , 'Cameroon' , 'Kamerun'),
('Kanada' , 'Canada' , 'Kanada'),
('Katar' , 'Qatar' , 'Katar'),
('Kazachstan' , 'Kazakhstan' , 'Kasachstan'),
('Kenia' , 'Kenya' , 'Kenia'),
('Kirgistan' , 'Kyrgyzstan' , 'Kirgisistan'),
('Kiribati' , 'Kiribati' , 'Kiribati'),
('Kolumbia' , 'Colombia' , 'Kolumbien'),
('Komory' , 'Comoros' , 'Komoren'),
('Kongo' , 'Congo' , 'Kongo, Demokratische Republik'),
('Korea Południowa' , 'Korea, Republic of' , 'Korea, Süd'),
('Korea Północna' , 'Korea, Democratic People`s Republic of' , 'Korea, Nord'),
('Kostaryka' , 'Costa Rica' , 'Costa Rica'),
('Kuba' , 'Cuba' , 'Kuba'),
('Kuwejt' , 'Kuwait' , 'Kuwait'),
('Laos' , 'Lao People`s Democratic Republic' , 'Laos'),
('Lesotho' , 'Lesotho' , 'Lesotho'),
('Liban' , 'Lebanon' , 'Libanon'),
('Liberia' , 'Liberia' , 'Liberia'),
('Libia' , 'Libyan Arab Jamahiriya' , 'Libyen'),
('Liechtenstein' , 'Liechtenstein' , 'Liechtenstein'),
('Litwa' , 'Lithuania' , 'Litauen'),
('Luksemburg' , 'Luxembourg' , 'Luxemburg'),
('Łotwa' , 'Latvia' , 'Lettland'),
('Macedonia' , 'Macedonia' , 'Mazedonien'),
('Madagaskar' , 'Madagascar' , 'Madagaskar'),
('Malawi' , 'Malawi' , 'Malawi'),
('Malediwy' , 'Maldives' , 'Malediven'),
('Malezja' , 'Malaysia' , 'Malaysia'),
('Mali' , 'Mali' , 'Mali'),
('Malta' , 'Malta' , 'Malta'),
('Maroko' , 'Morocco' , 'Marokko'),
('Mauretania' , 'Mauritania' , 'Mauretanien'),
('Mauritius' , 'Mauritius' , 'Mauritius'),
('Meksyk' , 'Mexico' , 'Mexiko'),
('Mikronezja' , 'Micronesia' , 'Mikronesien'),
('Mołdawia' , 'Moldova' , 'Moldawien'),
('Monako' , 'Monaco' , 'Monaco'),
('Mongolia' , 'Mongolia' , 'Mongolei'),
('Mozambik' , 'Mozambique' , 'Mosambik'),
('Namibia' , 'Namibia' , 'Namibia'),
('Nauru' , 'Nauru' , 'Nauru'),
('Nepal' , 'Nepal' , 'Nepal'),
('Niemcy' , 'Germany' , 'Deutschland'),
('Niger' , 'Niger' , 'Niger'),
('Nigeria' , 'Nigeria' , 'Nigeria'),
('Nikaragua' , 'Nicaragua' , 'Nicaragua'),
('Norwegia' , 'Norway' , 'Norwegen'),
('Nowa Zelandia' , 'New Zealand' , 'Neuseeland'),
('Oman' , 'Oman' , 'Oman'),
('Pakistan' , 'Pakistan' , 'Pakistan'),
('Palau' , 'Palau' , 'Palau'),
('Panama' , 'Panama' , 'Panama'),
('Papua-Nowa Gwinea' , 'Papua New Guinea' , 'Papua-Neuguinea'),
('Paragwaj' , 'Paraguay' , 'Paraguay'),
('Peru' , 'Peru' , 'Peru'),
('Polska' , 'Poland' , 'Polen'),
('Portugalia' , 'Portugal' , 'Portugal'),
('Republika Południowej Afryki' , 'South Africa' , 'Südafrika'),
('Republika Środkowoafrykańska' , 'Central African Republic' , 'Zentralafrikanische Republik'),
('Republika Zielonego Przylądka' , 'Cape Verde' , 'Kap Verde'),
('Rosja' , 'Russian Federation' , 'Russland'),
('Rumunia' , 'Romania' , 'Rumänien'),
('Rwanda' , 'Rwanda' , 'Ruanda'),
('Saint Kitts i Nevis' , 'Saint Kitts and Nevis' , 'St. Kitts und Nevis'),
('Saint Lucia' , 'Saint Lucia' , 'St. Lucia'),
('Saint Vincent i Grenadyny' , 'Saint Vincent and the Grenadines' , 'St. Vincent und die Grenadinen'),
('Salwador' , 'El Salvador' , 'El Salvador'),
('Samoa' , 'Samoa' , 'Samoa'),
('San Marino' , 'San Marino' , 'San Marino'),
('Senegal' , 'Senegal' , 'Senegal'),
('Serbia' , 'Serbia' , 'Serbien'),
('Seszele' , 'Seychelles' , 'Seychellen'),
('Sierra Leone' , 'Sierra Leone' , 'Sierra Leone'),
('Singapur' , 'Singapore' , 'Singapur'),
('Słowacja' , 'Slovakia' , 'Slowakei'),
('Słowenia' , 'Slovenia' , 'Slowenien'),
('Somalia' , 'Somalia' , 'Somalia'),
('Sri Lanka' , 'Sri Lanka' , 'Sri Lanka'),
('Stany Zjednoczone' , 'United States' , 'Vereinigte Staaten'),
('Suazi' , 'Swaziland' , 'Swasiland'),
('Sudan' , 'Sudan' , 'Sudan'),
('Surinam' , 'Suriname' , 'Suriname'),
('Syria' , 'Syrian Arab Republic' , 'Syrien'),
('Szwajcaria' , 'Switzerland' , 'Schweiz'),
('Szwecja' , 'Sweden' , 'Schweden'),
('Tadżykistan' , 'Tajikistan' , 'Tadschikistan'),
('Tajlandia' , 'Thailand' , 'Thailand'),
('Tanzania' , 'Tanzania' , 'Tansania'),
('Timor Wschodni' , 'Timor-Leste' , 'Osttimor / Timor-Leste'),
('Togo' , 'Togo' , 'Togo'),
('Tonga' , 'Tonga' , 'Tonga'),
('Trynidad i Tobago' , 'Trinidad and Tobago' , 'Trinidad und Tobago'),
('Tunezja' , 'Tunisia' , 'Tunesien'),
('Turcja' , 'Turkey' , 'Türkei'),
('Turkmenistan' , 'Turkmenistan' , 'Turkmenistan'),
('Tuvalu' , 'Tuvalu' , 'Tuvalu'),
('Uganda' , 'Uganda' , 'Uganda'),
('Ukraina' , 'Ukraine' , 'Ukraine'),
('Urugwaj' , 'Uruguay' , 'Uruguay'),
('Uzbekistan' , 'Uzbekistan' , 'Usbekistan'),
('Vanuatu' , 'Vanuatu' , 'Vanuatu'),
('Watykan' , 'Vatican' , 'Vatikan'),
('Wenezuela' , 'Venezuela' , 'Venezuela'),
('Węgry' , 'Hungary' , 'Ungarn'),
('Wielka Brytania' , 'United Kingdom' , 'Großbritannien'),
('Wietnam' , 'Viet Nam' , 'Vietnam'),
('Włochy' , 'Italy' , 'Italien'),
('Wybrzeże Kości Słoniowej' , 'Côte d`Ivoire' , 'Elfenbeinküste'),
('Wyspy Marshalla' , 'Marshall Islands' , 'Marshallinseln'),
('Wyspy Salomona' , 'Solomon Islands' , 'Salomonen'),
('Wyspy Świętego Tomasza i Książęca' , 'Sao Tome and Principe' , 'Sao Tomé und Príncipe'),
('Zambia' , 'Zambia' , 'Sambia'),
('Zimbabwe' , 'Zimbabwe' , 'Zimbabwe'),
('Zjednoczone Emiraty Arabskie' ,'United Arab Emirates' , 'Vereinigte Arabische Emirate'); 