INSERT INTO city(name,id_province) VALUES ('Aleksandrów Kujawski','2');
INSERT INTO city(name,id_province) VALUES ('Aleksandrów Łódzki','5');
INSERT INTO city(name,id_province) VALUES ('Alwernia','6');
INSERT INTO city(name,id_province) VALUES ('Andrychów','6');
INSERT INTO city(name,id_province) VALUES ('Annopol','3');
INSERT INTO city(name,id_province) VALUES ('Augustów','10');
INSERT INTO city(name,id_province) VALUES ('Babimost','4');
INSERT INTO city(name,id_province) VALUES ('Baborów','8');
INSERT INTO city(name,id_province) VALUES ('Baranów Sandomierski','9');
INSERT INTO city(name,id_province) VALUES ('Barcin','2');
INSERT INTO city(name,id_province) VALUES ('Barczewo','14');
INSERT INTO city(name,id_province) VALUES ('Bardo','1');
INSERT INTO city(name,id_province) VALUES ('Barlinek','16');
INSERT INTO city(name,id_province) VALUES ('Bartoszyce','14');
INSERT INTO city(name,id_province) VALUES ('Barwice','16');
INSERT INTO city(name,id_province) VALUES ('Bełchatów','5');
INSERT INTO city(name,id_province) VALUES ('Bełżyce','3');
INSERT INTO city(name,id_province) VALUES ('Będzin','12');
INSERT INTO city(name,id_province) VALUES ('Biała','8');
INSERT INTO city(name,id_province) VALUES ('Biała Piska','14');
INSERT INTO city(name,id_province) VALUES ('Biała Podlaska','3');
INSERT INTO city(name,id_province) VALUES ('Biała Rawska','5');
INSERT INTO city(name,id_province) VALUES ('Białobrzegi','7');
INSERT INTO city(name,id_province) VALUES ('Białogard','16');
INSERT INTO city(name,id_province) VALUES ('Biały Bór','16');
INSERT INTO city(name,id_province) VALUES ('Białystok','10');
INSERT INTO city(name,id_province) VALUES ('Biecz','6');
INSERT INTO city(name,id_province) VALUES ('Bielawa','1');
INSERT INTO city(name,id_province) VALUES ('Bielsk Podlaski','10');
INSERT INTO city(name,id_province) VALUES ('Bielsko-Biała','12');
INSERT INTO city(name,id_province) VALUES ('Bieruń','12');
INSERT INTO city(name,id_province) VALUES ('Bierutów','1');
INSERT INTO city(name,id_province) VALUES ('Bieżuń','7');
INSERT INTO city(name,id_province) VALUES ('Biłgoraj','3');
INSERT INTO city(name,id_province) VALUES ('Biskupiec','14');
INSERT INTO city(name,id_province) VALUES ('Bisztynek','14');
INSERT INTO city(name,id_province) VALUES ('Blachownia','12');
INSERT INTO city(name,id_province) VALUES ('Błaszki','5');
INSERT INTO city(name,id_province) VALUES ('Błażowa','9');
INSERT INTO city(name,id_province) VALUES ('Błonie','7');
INSERT INTO city(name,id_province) VALUES ('Bobolice','16');
INSERT INTO city(name,id_province) VALUES ('Bochnia','6');
INSERT INTO city(name,id_province) VALUES ('Bodzentyn','13');
INSERT INTO city(name,id_province) VALUES ('Bogatynia','1');
INSERT INTO city(name,id_province) VALUES ('Boguszów-Gorce','1');
INSERT INTO city(name,id_province) VALUES ('Bojanowo','15');
INSERT INTO city(name,id_province) VALUES ('Bolesławiec','1');
INSERT INTO city(name,id_province) VALUES ('Bolków','1');
INSERT INTO city(name,id_province) VALUES ('Borek Wielkopolski','15');
INSERT INTO city(name,id_province) VALUES ('Borne Sulinowo','16');
INSERT INTO city(name,id_province) VALUES ('Braniewo','14');
INSERT INTO city(name,id_province) VALUES ('Brańsk','10');
INSERT INTO city(name,id_province) VALUES ('Brodnica','2');
INSERT INTO city(name,id_province) VALUES ('Brok','7');
INSERT INTO city(name,id_province) VALUES ('Brusy','11');
INSERT INTO city(name,id_province) VALUES ('Brwinów','7');
INSERT INTO city(name,id_province) VALUES ('Brzeg','8');
INSERT INTO city(name,id_province) VALUES ('Brzeg Dolny','1');
INSERT INTO city(name,id_province) VALUES ('Brzesko','6');
INSERT INTO city(name,id_province) VALUES ('Brzeszcze','6');
INSERT INTO city(name,id_province) VALUES ('Brześć Kujawski','2');
INSERT INTO city(name,id_province) VALUES ('Brzeziny','5');
INSERT INTO city(name,id_province) VALUES ('Brzozów','9');
INSERT INTO city(name,id_province) VALUES ('Buk','15');
INSERT INTO city(name,id_province) VALUES ('Bukowno','6');
INSERT INTO city(name,id_province) VALUES ('Busko Zdrój','13');
INSERT INTO city(name,id_province) VALUES ('Bychawa','3');
INSERT INTO city(name,id_province) VALUES ('Byczyna','8');
INSERT INTO city(name,id_province) VALUES ('Bydgoszcz','2');
INSERT INTO city(name,id_province) VALUES ('Bystrzyca Kłodzka','1');
INSERT INTO city(name,id_province) VALUES ('Bytom','12');
INSERT INTO city(name,id_province) VALUES ('Bytom Odrzański','4');
INSERT INTO city(name,id_province) VALUES ('Bytów','11');
INSERT INTO city(name,id_province) VALUES ('Cedynia','16');
INSERT INTO city(name,id_province) VALUES ('Chełm','3');
INSERT INTO city(name,id_province) VALUES ('Chełmek','6');
INSERT INTO city(name,id_province) VALUES ('Chełmno','2');
INSERT INTO city(name,id_province) VALUES ('Chełmża','2');
INSERT INTO city(name,id_province) VALUES ('Chęciny','13');
INSERT INTO city(name,id_province) VALUES ('Chmielnik','13');
INSERT INTO city(name,id_province) VALUES ('Chocianów','1');
INSERT INTO city(name,id_province) VALUES ('Chociwel','16');
INSERT INTO city(name,id_province) VALUES ('Chodecz','2');
INSERT INTO city(name,id_province) VALUES ('Chodzież','15');
INSERT INTO city(name,id_province) VALUES ('Chojna','16');
INSERT INTO city(name,id_province) VALUES ('Chojnice','11');
INSERT INTO city(name,id_province) VALUES ('Chojnów','1');
INSERT INTO city(name,id_province) VALUES ('Choroszcz','10');
INSERT INTO city(name,id_province) VALUES ('Chorzele','7');
INSERT INTO city(name,id_province) VALUES ('Chorzów','12');
INSERT INTO city(name,id_province) VALUES ('Choszczno','16');
INSERT INTO city(name,id_province) VALUES ('Chrzanów','6');
INSERT INTO city(name,id_province) VALUES ('Ciechanowiec','10');
INSERT INTO city(name,id_province) VALUES ('Ciechanów','7');
INSERT INTO city(name,id_province) VALUES ('Ciechocinek','2');
INSERT INTO city(name,id_province) VALUES ('Cieszanów','9');
INSERT INTO city(name,id_province) VALUES ('Cieszyn','12');
INSERT INTO city(name,id_province) VALUES ('Ciężkowice','6');
INSERT INTO city(name,id_province) VALUES ('Cybinka','4');
INSERT INTO city(name,id_province) VALUES ('Czaplinek','16');
INSERT INTO city(name,id_province) VALUES ('Czarna Białostocka','10');
INSERT INTO city(name,id_province) VALUES ('Czarna Woda','11');
INSERT INTO city(name,id_province) VALUES ('Czarne','11');
INSERT INTO city(name,id_province) VALUES ('Czarnków','15');
INSERT INTO city(name,id_province) VALUES ('Czchów','6');
INSERT INTO city(name,id_province) VALUES ('Czechowice-Dziedzice','12');
INSERT INTO city(name,id_province) VALUES ('Czeladź','12');
INSERT INTO city(name,id_province) VALUES ('Czempiń','15');
INSERT INTO city(name,id_province) VALUES ('Czerniejewo','15');
INSERT INTO city(name,id_province) VALUES ('Czersk','11');
INSERT INTO city(name,id_province) VALUES ('Czerwieńsk','4');
INSERT INTO city(name,id_province) VALUES ('Czerwionka-Leszczyny','12');
INSERT INTO city(name,id_province) VALUES ('Częstochowa','12');
INSERT INTO city(name,id_province) VALUES ('Człopa','16');
INSERT INTO city(name,id_province) VALUES ('Człuchów','11');
INSERT INTO city(name,id_province) VALUES ('Ćmielów','13');
INSERT INTO city(name,id_province) VALUES ('Darłowo','16');
INSERT INTO city(name,id_province) VALUES ('Dąbie','15');
INSERT INTO city(name,id_province) VALUES ('Dąbrowa Białostocka','10');
INSERT INTO city(name,id_province) VALUES ('Dąbrowa Górnicza','12');
INSERT INTO city(name,id_province) VALUES ('Dąbrowa Tarnowska','6');
INSERT INTO city(name,id_province) VALUES ('Debrzno','11');
INSERT INTO city(name,id_province) VALUES ('Dębica','9');
INSERT INTO city(name,id_province) VALUES ('Dęblin','3');
INSERT INTO city(name,id_province) VALUES ('Dębno','16');
INSERT INTO city(name,id_province) VALUES ('Dobczyce','6');
INSERT INTO city(name,id_province) VALUES ('Dobiegniew','4');
INSERT INTO city(name,id_province) VALUES ('Dobra','15');
INSERT INTO city(name,id_province) VALUES ('Dobra','16');
INSERT INTO city(name,id_province) VALUES ('Dobre name','14');
INSERT INTO city(name,id_province) VALUES ('Dobrodzień','8');
INSERT INTO city(name,id_province) VALUES ('Dobrzany','16');
INSERT INTO city(name,id_province) VALUES ('Dobrzyń nad Wisłą','2');
INSERT INTO city(name,id_province) VALUES ('Dolsk','15');
INSERT INTO city(name,id_province) VALUES ('Drawno','16');
INSERT INTO city(name,id_province) VALUES ('Drawsko 11','16');
INSERT INTO city(name,id_province) VALUES ('Drezdenko','4');
INSERT INTO city(name,id_province) VALUES ('Drobin','7');
INSERT INTO city(name,id_province) VALUES ('Drohiczyn','10');
INSERT INTO city(name,id_province) VALUES ('Drzewica','5');
INSERT INTO city(name,id_province) VALUES ('Dukla','9');
INSERT INTO city(name,id_province) VALUES ('Duszniki Zdrój','1');
INSERT INTO city(name,id_province) VALUES ('Dynów','9');
INSERT INTO city(name,id_province) VALUES ('Działdowo','14');
INSERT INTO city(name,id_province) VALUES ('Działoszyce','13');
INSERT INTO city(name,id_province) VALUES ('Działoszyn','5');
INSERT INTO city(name,id_province) VALUES ('Dzierzgoń','11');
INSERT INTO city(name,id_province) VALUES ('Dzierżoniów','1');
INSERT INTO city(name,id_province) VALUES ('Elbląg','14');
INSERT INTO city(name,id_province) VALUES ('Ełk','14');
INSERT INTO city(name,id_province) VALUES ('Frampol','3');
INSERT INTO city(name,id_province) VALUES ('Frombork','14');
INSERT INTO city(name,id_province) VALUES ('Garwolin','7');
INSERT INTO city(name,id_province) VALUES ('Gąbin','7');
INSERT INTO city(name,id_province) VALUES ('Gdańsk','11');
INSERT INTO city(name,id_province) VALUES ('Gdynia','11');
INSERT INTO city(name,id_province) VALUES ('Giżycko','14');
INSERT INTO city(name,id_province) VALUES ('Glinojeck','7');
INSERT INTO city(name,id_province) VALUES ('Gliwice','12');
INSERT INTO city(name,id_province) VALUES ('Głogów','1');
INSERT INTO city(name,id_province) VALUES ('Głogów Małopolski','9');
INSERT INTO city(name,id_province) VALUES ('Głogówek','8');
INSERT INTO city(name,id_province) VALUES ('Głowno','5');
INSERT INTO city(name,id_province) VALUES ('Głubczyce','8');
INSERT INTO city(name,id_province) VALUES ('Głuchołazy','8');
INSERT INTO city(name,id_province) VALUES ('Głuszyca','1');
INSERT INTO city(name,id_province) VALUES ('Gniew','11');
INSERT INTO city(name,id_province) VALUES ('Gniewkowo','2');
INSERT INTO city(name,id_province) VALUES ('Gniezno','15');
INSERT INTO city(name,id_province) VALUES ('Gogolin','8');
INSERT INTO city(name,id_province) VALUES ('Golczewo','16');
INSERT INTO city(name,id_province) VALUES ('Goleniów','16');
INSERT INTO city(name,id_province) VALUES ('Golina','15');
INSERT INTO city(name,id_province) VALUES ('Golub-Dobrzyń','2');
INSERT INTO city(name,id_province) VALUES ('Gołańcz','15');
INSERT INTO city(name,id_province) VALUES ('Gołdap','14');
INSERT INTO city(name,id_province) VALUES ('Goniądz','10');
INSERT INTO city(name,id_province) VALUES ('Gorlice','6');
INSERT INTO city(name,id_province) VALUES ('Gorzów Śląski','8');
INSERT INTO city(name,id_province) VALUES ('Gorzów Wielkopolski','4');
INSERT INTO city(name,id_province) VALUES ('Gostynin','7');
INSERT INTO city(name,id_province) VALUES ('Gostyń','15');
INSERT INTO city(name,id_province) VALUES ('Gozdnica','4');
INSERT INTO city(name,id_province) VALUES ('Góra','1');
INSERT INTO city(name,id_province) VALUES ('Góra Kalwaria','7');
INSERT INTO city(name,id_province) VALUES ('Górowo Iławeckie','14');
INSERT INTO city(name,id_province) VALUES ('Górzno','2');
INSERT INTO city(name,id_province) VALUES ('Grabów nad Prosną','15');
INSERT INTO city(name,id_province) VALUES ('Grajewo','10');
INSERT INTO city(name,id_province) VALUES ('Grodków','8');
INSERT INTO city(name,id_province) VALUES ('Grodzisk Mazowiecki','7');
INSERT INTO city(name,id_province) VALUES ('Grodzisk Wielkopolski','15');
INSERT INTO city(name,id_province) VALUES ('Grójec','7');
INSERT INTO city(name,id_province) VALUES ('Grudziądz','2');
INSERT INTO city(name,id_province) VALUES ('Grybów','6');
INSERT INTO city(name,id_province) VALUES ('Gryfice','16');
INSERT INTO city(name,id_province) VALUES ('Gryfino','16');
INSERT INTO city(name,id_province) VALUES ('Gryfów Śląski','1');
INSERT INTO city(name,id_province) VALUES ('Gubin','4');
INSERT INTO city(name,id_province) VALUES ('Hajnówka','10');
INSERT INTO city(name,id_province) VALUES ('Hel','11');
INSERT INTO city(name,id_province) VALUES ('Hrubieszów','3');
INSERT INTO city(name,id_province) VALUES ('Iława','14');
INSERT INTO city(name,id_province) VALUES ('Iłowa','4');
INSERT INTO city(name,id_province) VALUES ('Iłża','7');
INSERT INTO city(name,id_province) VALUES ('Imielin','12');
INSERT INTO city(name,id_province) VALUES ('Inowrocław','2');
INSERT INTO city(name,id_province) VALUES ('Ińsko','16');
INSERT INTO city(name,id_province) VALUES ('Iwonicz Zdrój','9');
INSERT INTO city(name,id_province) VALUES ('Izbica Kujawska','2');
INSERT INTO city(name,id_province) VALUES ('Jabłonowo 11','2');
INSERT INTO city(name,id_province) VALUES ('Janikowo','2');
INSERT INTO city(name,id_province) VALUES ('Janowiec Wielkopolski','2');
INSERT INTO city(name,id_province) VALUES ('Janów Lubelski','3');
INSERT INTO city(name,id_province) VALUES ('Jarocin','15');
INSERT INTO city(name,id_province) VALUES ('Jarosław','9');
INSERT INTO city(name,id_province) VALUES ('Jasień','4');
INSERT INTO city(name,id_province) VALUES ('Jasło','9');
INSERT INTO city(name,id_province) VALUES ('Jastarnia','11');
INSERT INTO city(name,id_province) VALUES ('Jastrowie','15');
INSERT INTO city(name,id_province) VALUES ('Jastrzębie Zdrój','12');
INSERT INTO city(name,id_province) VALUES ('Jawor','1');
INSERT INTO city(name,id_province) VALUES ('Jaworzno','12');
INSERT INTO city(name,id_province) VALUES ('Jaworzyna Śląska','1');
INSERT INTO city(name,id_province) VALUES ('Jedlicze','9');
INSERT INTO city(name,id_province) VALUES ('Jedlina Zdrój','1');
INSERT INTO city(name,id_province) VALUES ('Jedwabne','10');
INSERT INTO city(name,id_province) VALUES ('Jelcz-Laskowice','1');
INSERT INTO city(name,id_province) VALUES ('Jelenia Góra','1');
INSERT INTO city(name,id_province) VALUES ('Jeziorany','14');
INSERT INTO city(name,id_province) VALUES ('Jędrzejów','13');
INSERT INTO city(name,id_province) VALUES ('Jordanów','6');
INSERT INTO city(name,id_province) VALUES ('Józefów','3');
INSERT INTO city(name,id_province) VALUES ('Józefów','7');
INSERT INTO city(name,id_province) VALUES ('Jutrosin','15');
INSERT INTO city(name,id_province) VALUES ('Kalety','12');
INSERT INTO city(name,id_province) VALUES ('Kalisz','15');
INSERT INTO city(name,id_province) VALUES ('Kalisz Pomorski','16');
INSERT INTO city(name,id_province) VALUES ('Kalwaria Zebrzydowska','6');
INSERT INTO city(name,id_province) VALUES ('Kałuszyn','7');
INSERT INTO city(name,id_province) VALUES ('Kamienna Góra','1');
INSERT INTO city(name,id_province) VALUES ('Kamień Krajeński','2');
INSERT INTO city(name,id_province) VALUES ('Kamień Pomorski','16');
INSERT INTO city(name,id_province) VALUES ('Kamieńsk','5');
INSERT INTO city(name,id_province) VALUES ('Kańczuga','9');
INSERT INTO city(name,id_province) VALUES ('Karczew','7');
INSERT INTO city(name,id_province) VALUES ('Kargowa','4');
INSERT INTO city(name,id_province) VALUES ('Karlino','16');
INSERT INTO city(name,id_province) VALUES ('Karpacz','1');
INSERT INTO city(name,id_province) VALUES ('Kartuzy','11');
INSERT INTO city(name,id_province) VALUES ('Katowice','12');
INSERT INTO city(name,id_province) VALUES ('Kazimierz Dolny','3');
INSERT INTO city(name,id_province) VALUES ('Kazimierza Wielka','13');
INSERT INTO city(name,id_province) VALUES ('Kąty Wrocławskie','1');
INSERT INTO city(name,id_province) VALUES ('Kcynia','2');
INSERT INTO city(name,id_province) VALUES ('Kędzierzyn-Koźle','8');
INSERT INTO city(name,id_province) VALUES ('Kępice','16');
INSERT INTO city(name,id_province) VALUES ('Kępno','15');
INSERT INTO city(name,id_province) VALUES ('Kętrzyn','14');
INSERT INTO city(name,id_province) VALUES ('Kęty','6');
INSERT INTO city(name,id_province) VALUES ('Kielce','13');
INSERT INTO city(name,id_province) VALUES ('Kietrz','8');
INSERT INTO city(name,id_province) VALUES ('Kisielice','14');
INSERT INTO city(name,id_province) VALUES ('Kleczew','15');
INSERT INTO city(name,id_province) VALUES ('Kleszczele','10');
INSERT INTO city(name,id_province) VALUES ('Kluczbork','8');
INSERT INTO city(name,id_province) VALUES ('Kłecko','15');
INSERT INTO city(name,id_province) VALUES ('Kłobuck','12');
INSERT INTO city(name,id_province) VALUES ('Kłodawa','15');
INSERT INTO city(name,id_province) VALUES ('Kłodzko','1');
INSERT INTO city(name,id_province) VALUES ('Knurów','12');
INSERT INTO city(name,id_province) VALUES ('Knyszyn','10');
INSERT INTO city(name,id_province) VALUES ('Kobylin','15');
INSERT INTO city(name,id_province) VALUES ('Kobyłka','7');
INSERT INTO city(name,id_province) VALUES ('Kock','3');
INSERT INTO city(name,id_province) VALUES ('Kolbuszowa','9');
INSERT INTO city(name,id_province) VALUES ('Kolno','10');
INSERT INTO city(name,id_province) VALUES ('Kolonowskie','8');
INSERT INTO city(name,id_province) VALUES ('Koluszki','5');
INSERT INTO city(name,id_province) VALUES ('Koło','15');
INSERT INTO city(name,id_province) VALUES ('Kołobrzeg','16');
INSERT INTO city(name,id_province) VALUES ('Koniecpol','12');
INSERT INTO city(name,id_province) VALUES ('Konin','15');
INSERT INTO city(name,id_province) VALUES ('Konstancin-Jeziorna','7');
INSERT INTO city(name,id_province) VALUES ('Konstantynów Łódzki','5');
INSERT INTO city(name,id_province) VALUES ('Końskie','13');
INSERT INTO city(name,id_province) VALUES ('Korfantów','8');
INSERT INTO city(name,id_province) VALUES ('Koronowo','2');
INSERT INTO city(name,id_province) VALUES ('Korsze','14');
INSERT INTO city(name,id_province) VALUES ('Kosów Lacki','7');
INSERT INTO city(name,id_province) VALUES ('Kostrzyn','4');
INSERT INTO city(name,id_province) VALUES ('Kostrzyn','15');
INSERT INTO city(name,id_province) VALUES ('Koszalin','16');
INSERT INTO city(name,id_province) VALUES ('Kościan','15');
INSERT INTO city(name,id_province) VALUES ('Kościerzyna','11');
INSERT INTO city(name,id_province) VALUES ('Kowal','2');
INSERT INTO city(name,id_province) VALUES ('Kowalewo 11','2');
INSERT INTO city(name,id_province) VALUES ('Kowary','1');
INSERT INTO city(name,id_province) VALUES ('Koziegłowy','12');
INSERT INTO city(name,id_province) VALUES ('Kozienice','7');
INSERT INTO city(name,id_province) VALUES ('Koźmin Wielkopolski','15');
INSERT INTO city(name,id_province) VALUES ('Kożuchów','4');
INSERT INTO city(name,id_province) VALUES ('Kórnik','15');
INSERT INTO city(name,id_province) VALUES ('Krajenka','15');
INSERT INTO city(name,id_province) VALUES ('Kraków','6');
INSERT INTO city(name,id_province) VALUES ('Krapkowice','8');
INSERT INTO city(name,id_province) VALUES ('Krasnobród','3');
INSERT INTO city(name,id_province) VALUES ('Krasnystaw','3');
INSERT INTO city(name,id_province) VALUES ('Kraśnik','3');
INSERT INTO city(name,id_province) VALUES ('Krobia','15');
INSERT INTO city(name,id_province) VALUES ('Krosno','9');
INSERT INTO city(name,id_province) VALUES ('Krosno Odrzańskie','4');
INSERT INTO city(name,id_province) VALUES ('Krośniewice','5');
INSERT INTO city(name,id_province) VALUES ('Krotoszyn','15');
INSERT INTO city(name,id_province) VALUES ('Kruszwica','2');
INSERT INTO city(name,id_province) VALUES ('Krynica','6');
INSERT INTO city(name,id_province) VALUES ('Krynica Morska','11');
INSERT INTO city(name,id_province) VALUES ('Krzepice','12');
INSERT INTO city(name,id_province) VALUES ('Krzeszowice','6');
INSERT INTO city(name,id_province) VALUES ('Krzywiń','15');
INSERT INTO city(name,id_province) VALUES ('Krzyż Wielkopolski','15');
INSERT INTO city(name,id_province) VALUES ('Książ Wielkopolski','15');
INSERT INTO city(name,id_province) VALUES ('Kudowa Zdrój','1');
INSERT INTO city(name,id_province) VALUES ('Kunów','13');
INSERT INTO city(name,id_province) VALUES ('Kutno','5');
INSERT INTO city(name,id_province) VALUES ('Kuźnia Raciborska','12');
INSERT INTO city(name,id_province) VALUES ('Kwidzyn','11');
INSERT INTO city(name,id_province) VALUES ('Lądek Zdrój','1');
INSERT INTO city(name,id_province) VALUES ('Legionowo','7');
INSERT INTO city(name,id_province) VALUES ('Legnica','1');
INSERT INTO city(name,id_province) VALUES ('Lesko','9');
INSERT INTO city(name,id_province) VALUES ('Leszno','15');
INSERT INTO city(name,id_province) VALUES ('Leśna','1');
INSERT INTO city(name,id_province) VALUES ('Leśnica','8');
INSERT INTO city(name,id_province) VALUES ('Lewin Brzeski','8');
INSERT INTO city(name,id_province) VALUES ('Leżajsk','9');
INSERT INTO city(name,id_province) VALUES ('Lębork','11');
INSERT INTO city(name,id_province) VALUES ('Lędziny','12');
INSERT INTO city(name,id_province) VALUES ('Libiąż','6');
INSERT INTO city(name,id_province) VALUES ('Lidzbark','14');
INSERT INTO city(name,id_province) VALUES ('Lidzbark Warmiński','14');
INSERT INTO city(name,id_province) VALUES ('Limanowa','6');
INSERT INTO city(name,id_province) VALUES ('Lipiany','16');
INSERT INTO city(name,id_province) VALUES ('Lipno','2');
INSERT INTO city(name,id_province) VALUES ('Lipsk','10');
INSERT INTO city(name,id_province) VALUES ('Lipsko','7');
INSERT INTO city(name,id_province) VALUES ('Lubaczów','9');
INSERT INTO city(name,id_province) VALUES ('Lubań','1');
INSERT INTO city(name,id_province) VALUES ('Lubartów','3');
INSERT INTO city(name,id_province) VALUES ('Lubawa','14');
INSERT INTO city(name,id_province) VALUES ('Lubawka','1');
INSERT INTO city(name,id_province) VALUES ('Lubień Kujawski','2');
INSERT INTO city(name,id_province) VALUES ('Lubin','1');
INSERT INTO city(name,id_province) VALUES ('Lublin','3');
INSERT INTO city(name,id_province) VALUES ('Lubliniec','12');
INSERT INTO city(name,id_province) VALUES ('Lubniewice','4');
INSERT INTO city(name,id_province) VALUES ('Lubomierz','1');
INSERT INTO city(name,id_province) VALUES ('Luboń','15');
INSERT INTO city(name,id_province) VALUES ('Lubraniec','2');
INSERT INTO city(name,id_province) VALUES ('Lubsko','4');
INSERT INTO city(name,id_province) VALUES ('Lwówek','15');
INSERT INTO city(name,id_province) VALUES ('Lwówek Śląski','1');
INSERT INTO city(name,id_province) VALUES ('Łabiszyn','2');
INSERT INTO city(name,id_province) VALUES ('Łańcut','9');
INSERT INTO city(name,id_province) VALUES ('Łapy','10');
INSERT INTO city(name,id_province) VALUES ('Łasin','2');
INSERT INTO city(name,id_province) VALUES ('Łask','5');
INSERT INTO city(name,id_province) VALUES ('Łaskarzew','7');
INSERT INTO city(name,id_province) VALUES ('Łaziska Górne','12');
INSERT INTO city(name,id_province) VALUES ('Łazy','12');
INSERT INTO city(name,id_province) VALUES ('Łeba','11');
INSERT INTO city(name,id_province) VALUES ('Łęczna','3');
INSERT INTO city(name,id_province) VALUES ('Łęczyca','5');
INSERT INTO city(name,id_province) VALUES ('Łęknica','4');
INSERT INTO city(name,id_province) VALUES ('Łobez','16');
INSERT INTO city(name,id_province) VALUES ('Łobżenica','15');
INSERT INTO city(name,id_province) VALUES ('Łochów','7');
INSERT INTO city(name,id_province) VALUES ('Łomianki','7');
INSERT INTO city(name,id_province) VALUES ('Łomża','10');
INSERT INTO city(name,id_province) VALUES ('Łosice','7');
INSERT INTO city(name,id_province) VALUES ('Łowicz','5');
INSERT INTO city(name,id_province) VALUES ('Łódź','5');
INSERT INTO city(name,id_province) VALUES ('Łuków','3');
INSERT INTO city(name,id_province) VALUES ('Maków Mazowiecki','7');
INSERT INTO city(name,id_province) VALUES ('Maków Podhalański','6');
INSERT INTO city(name,id_province) VALUES ('Malbork','11');
INSERT INTO city(name,id_province) VALUES ('Małogoszcz','13');
INSERT INTO city(name,id_province) VALUES ('Małomice','4');
INSERT INTO city(name,id_province) VALUES ('Margonin','15');
INSERT INTO city(name,id_province) VALUES ('Marki','7');
INSERT INTO city(name,id_province) VALUES ('Maszewo','16');
INSERT INTO city(name,id_province) VALUES ('Miasteczko 12','12');
INSERT INTO city(name,id_province) VALUES ('Miastko','11');
INSERT INTO city(name,id_province) VALUES ('Miechów','6');
INSERT INTO city(name,id_province) VALUES ('Miejska Górka','15');
INSERT INTO city(name,id_province) VALUES ('Mielec','9');
INSERT INTO city(name,id_province) VALUES ('Mieroszów','1');
INSERT INTO city(name,id_province) VALUES ('Mieszkowice','16');
INSERT INTO city(name,id_province) VALUES ('Międzybórz','1');
INSERT INTO city(name,id_province) VALUES ('Międzychód','15');
INSERT INTO city(name,id_province) VALUES ('Międzylesie','1');
INSERT INTO city(name,id_province) VALUES ('Międzyrzec Podlaski','3');
INSERT INTO city(name,id_province) VALUES ('Międzyrzecz','4');
INSERT INTO city(name,id_province) VALUES ('Międzyzdroje','16');
INSERT INTO city(name,id_province) VALUES ('Mikołajki','14');
INSERT INTO city(name,id_province) VALUES ('Mikołów','12');
INSERT INTO city(name,id_province) VALUES ('Mikstat','15');
INSERT INTO city(name,id_province) VALUES ('Milanówek','7');
INSERT INTO city(name,id_province) VALUES ('Milicz','1');
INSERT INTO city(name,id_province) VALUES ('Miłakowo','14');
INSERT INTO city(name,id_province) VALUES ('Miłomłyn','14');
INSERT INTO city(name,id_province) VALUES ('Miłosław','15');
INSERT INTO city(name,id_province) VALUES ('Mińsk Mazowiecki','7');
INSERT INTO city(name,id_province) VALUES ('Mirosławiec','16');
INSERT INTO city(name,id_province) VALUES ('Mirsk','1');
INSERT INTO city(name,id_province) VALUES ('Mława','7');
INSERT INTO city(name,id_province) VALUES ('Młynary','14');
INSERT INTO city(name,id_province) VALUES ('Mogielnica','7');
INSERT INTO city(name,id_province) VALUES ('Mogilno','2');
INSERT INTO city(name,id_province) VALUES ('Mońki','10');
INSERT INTO city(name,id_province) VALUES ('Morąg','14');
INSERT INTO city(name,id_province) VALUES ('Mordy','7');
INSERT INTO city(name,id_province) VALUES ('Moryń','16');
INSERT INTO city(name,id_province) VALUES ('Mosina','15');
INSERT INTO city(name,id_province) VALUES ('Mrągowo','14');
INSERT INTO city(name,id_province) VALUES ('Mrocza','2');
INSERT INTO city(name,id_province) VALUES ('Mszana Dolna','6');
INSERT INTO city(name,id_province) VALUES ('Mszczonów','7');
INSERT INTO city(name,id_province) VALUES ('Murowana Goślina','15');
INSERT INTO city(name,id_province) VALUES ('Muszyna','6');
INSERT INTO city(name,id_province) VALUES ('Mysłowice','12');
INSERT INTO city(name,id_province) VALUES ('Myszków','12');
INSERT INTO city(name,id_province) VALUES ('Myszyniec','7');
INSERT INTO city(name,id_province) VALUES ('Myślenice','6');
INSERT INTO city(name,id_province) VALUES ('Myślibórz','16');
INSERT INTO city(name,id_province) VALUES ('Nakło nad Notecią','2');
INSERT INTO city(name,id_province) VALUES ('Nałęczów','3');
INSERT INTO city(name,id_province) VALUES ('Namysłów','8');
INSERT INTO city(name,id_province) VALUES ('Narol','9');
INSERT INTO city(name,id_province) VALUES ('Nasielsk','7');
INSERT INTO city(name,id_province) VALUES ('Nekla','15');
INSERT INTO city(name,id_province) VALUES ('Nidzica','14');
INSERT INTO city(name,id_province) VALUES ('Niemcza','1');
INSERT INTO city(name,id_province) VALUES ('Niemodlin','8');
INSERT INTO city(name,id_province) VALUES ('Niepołomice','6');
INSERT INTO city(name,id_province) VALUES ('Nieszawa','2');
INSERT INTO city(name,id_province) VALUES ('Nisko','9');
INSERT INTO city(name,id_province) VALUES ('Nowa Dęba','9');
INSERT INTO city(name,id_province) VALUES ('Nowa Ruda','1');
INSERT INTO city(name,id_province) VALUES ('Nowa Sarzyna','9');
INSERT INTO city(name,id_province) VALUES ('Nowa Sól','4');
INSERT INTO city(name,id_province) VALUES ('Nowe','2');
INSERT INTO city(name,id_province) VALUES ('Nowe Miasteczko','4');
INSERT INTO city(name,id_province) VALUES ('Nowe name Lubawskie','14');
INSERT INTO city(name,id_province) VALUES ('Nowe name nad Pilicą','7');
INSERT INTO city(name,id_province) VALUES ('Nowe Skalmierzyce','15');
INSERT INTO city(name,id_province) VALUES ('Nowe Warpno','16');
INSERT INTO city(name,id_province) VALUES ('Nowogard','16');
INSERT INTO city(name,id_province) VALUES ('Nowogrodziec','1');
INSERT INTO city(name,id_province) VALUES ('Nowogród','10');
INSERT INTO city(name,id_province) VALUES ('Nowogród Bobrzański','4');
INSERT INTO city(name,id_province) VALUES ('Nowy Dwór Gdański','11');
INSERT INTO city(name,id_province) VALUES ('Nowy Dwór Mazowiecki','7');
INSERT INTO city(name,id_province) VALUES ('Nowy Sącz','6');
INSERT INTO city(name,id_province) VALUES ('Nowy Staw','11');
INSERT INTO city(name,id_province) VALUES ('Nowy Targ','6');
INSERT INTO city(name,id_province) VALUES ('Nowy Tomyśl','15');
INSERT INTO city(name,id_province) VALUES ('Nowy Wiśnicz','6');
INSERT INTO city(name,id_province) VALUES ('Nysa','8');
INSERT INTO city(name,id_province) VALUES ('Oborniki','15');
INSERT INTO city(name,id_province) VALUES ('Oborniki 12','1');
INSERT INTO city(name,id_province) VALUES ('Obrzycko','15');
INSERT INTO city(name,id_province) VALUES ('Odolanów','15');
INSERT INTO city(name,id_province) VALUES ('Ogrodzieniec','12');
INSERT INTO city(name,id_province) VALUES ('Okonek','15');
INSERT INTO city(name,id_province) VALUES ('Olecko','14');
INSERT INTO city(name,id_province) VALUES ('Olesno','8');
INSERT INTO city(name,id_province) VALUES ('Oleszyce','9');
INSERT INTO city(name,id_province) VALUES ('Oleśnica','1');
INSERT INTO city(name,id_province) VALUES ('Olkusz','6');
INSERT INTO city(name,id_province) VALUES ('Olsztyn','14');
INSERT INTO city(name,id_province) VALUES ('Olsztynek','14');
INSERT INTO city(name,id_province) VALUES ('Oława','1');
INSERT INTO city(name,id_province) VALUES ('Opalenica','15');
INSERT INTO city(name,id_province) VALUES ('Opatów','13');
INSERT INTO city(name,id_province) VALUES ('Opoczno','5');
INSERT INTO city(name,id_province) VALUES ('Opole','8');
INSERT INTO city(name,id_province) VALUES ('Opole 3','3');
INSERT INTO city(name,id_province) VALUES ('Orneta','14');
INSERT INTO city(name,id_province) VALUES ('Orzesze','12');
INSERT INTO city(name,id_province) VALUES ('Orzysz','14');
INSERT INTO city(name,id_province) VALUES ('Osieczna','15');
INSERT INTO city(name,id_province) VALUES ('Osiek','13');
INSERT INTO city(name,id_province) VALUES ('Ostrołęka','7');
INSERT INTO city(name,id_province) VALUES ('Ostroróg','15');
INSERT INTO city(name,id_province) VALUES ('Ostrowiec Świętokrzyski','13');
INSERT INTO city(name,id_province) VALUES ('Ostróda','14');
INSERT INTO city(name,id_province) VALUES ('Ostrów Lubelski','3');
INSERT INTO city(name,id_province) VALUES ('Ostrów Mazowiecka','7');
INSERT INTO city(name,id_province) VALUES ('Ostrów Wielkopolski','15');
INSERT INTO city(name,id_province) VALUES ('Ostrzeszów','15');
INSERT INTO city(name,id_province) VALUES ('Ośno 4','4');
INSERT INTO city(name,id_province) VALUES ('Oświęcim','6');
INSERT INTO city(name,id_province) VALUES ('Otmuchów','8');
INSERT INTO city(name,id_province) VALUES ('Otwock','7');
INSERT INTO city(name,id_province) VALUES ('Ozimek','8');
INSERT INTO city(name,id_province) VALUES ('Ozorków','5');
INSERT INTO city(name,id_province) VALUES ('Ożarów','13');
INSERT INTO city(name,id_province) VALUES ('Ożarów Mazowiecki','7');
INSERT INTO city(name,id_province) VALUES ('Pabianice','5');
INSERT INTO city(name,id_province) VALUES ('Paczków','8');
INSERT INTO city(name,id_province) VALUES ('Pajęczno','5');
INSERT INTO city(name,id_province) VALUES ('Pakość','2');
INSERT INTO city(name,id_province) VALUES ('Parczew','3');
INSERT INTO city(name,id_province) VALUES ('Pasłęk','14');
INSERT INTO city(name,id_province) VALUES ('Pasym','14');
INSERT INTO city(name,id_province) VALUES ('Pelplin','11');
INSERT INTO city(name,id_province) VALUES ('Pełczyce','16');
INSERT INTO city(name,id_province) VALUES ('Piaseczno','7');
INSERT INTO city(name,id_province) VALUES ('Piaski','3');
INSERT INTO city(name,id_province) VALUES ('Piastów','7');
INSERT INTO city(name,id_province) VALUES ('Piechowice','1');
INSERT INTO city(name,id_province) VALUES ('Piekary 12','12');
INSERT INTO city(name,id_province) VALUES ('Pieniężno','14');
INSERT INTO city(name,id_province) VALUES ('Pieńsk','1');
INSERT INTO city(name,id_province) VALUES ('Pieszyce','1');
INSERT INTO city(name,id_province) VALUES ('Pilawa','7');
INSERT INTO city(name,id_province) VALUES ('Pilica','12');
INSERT INTO city(name,id_province) VALUES ('Pilzno','9');
INSERT INTO city(name,id_province) VALUES ('Piła','15');
INSERT INTO city(name,id_province) VALUES ('Piława Górna','1');
INSERT INTO city(name,id_province) VALUES ('Pińczów','13');
INSERT INTO city(name,id_province) VALUES ('Pionki','7');
INSERT INTO city(name,id_province) VALUES ('Piotrków Kujawski','2');
INSERT INTO city(name,id_province) VALUES ('Piotrków Trybunalski','5');
INSERT INTO city(name,id_province) VALUES ('Pisz','14');
INSERT INTO city(name,id_province) VALUES ('Piwniczna Zdrój','6');
INSERT INTO city(name,id_province) VALUES ('Pleszew','15');
INSERT INTO city(name,id_province) VALUES ('Płock','7');
INSERT INTO city(name,id_province) VALUES ('Płońsk','7');
INSERT INTO city(name,id_province) VALUES ('Płoty','16');
INSERT INTO city(name,id_province) VALUES ('Pniewy','15');
INSERT INTO city(name,id_province) VALUES ('Pobiedziska','15');
INSERT INTO city(name,id_province) VALUES ('Poddębice','5');
INSERT INTO city(name,id_province) VALUES ('Podkowa Leśna','7');
INSERT INTO city(name,id_province) VALUES ('Pogorzela','15');
INSERT INTO city(name,id_province) VALUES ('Polanica Zdrój','1');
INSERT INTO city(name,id_province) VALUES ('Polanów','16');
INSERT INTO city(name,id_province) VALUES ('Police','16');
INSERT INTO city(name,id_province) VALUES ('Polkowice','1');
INSERT INTO city(name,id_province) VALUES ('Połaniec','13');
INSERT INTO city(name,id_province) VALUES ('Połczyn Zdrój','16');
INSERT INTO city(name,id_province) VALUES ('Poniatowa','3');
INSERT INTO city(name,id_province) VALUES ('Poniec','15');
INSERT INTO city(name,id_province) VALUES ('Poręba','12');
INSERT INTO city(name,id_province) VALUES ('Poznań','15');
INSERT INTO city(name,id_province) VALUES ('Prabuty','11');
INSERT INTO city(name,id_province) VALUES ('Praszka','8');
INSERT INTO city(name,id_province) VALUES ('Prochowice','1');
INSERT INTO city(name,id_province) VALUES ('Proszowice','6');
INSERT INTO city(name,id_province) VALUES ('Prudnik','8');
INSERT INTO city(name,id_province) VALUES ('Prusice','1');
INSERT INTO city(name,id_province) VALUES ('Pruszcz Gdański','11');
INSERT INTO city(name,id_province) VALUES ('Pruszków','7');
INSERT INTO city(name,id_province) VALUES ('Przasnysz','7');
INSERT INTO city(name,id_province) VALUES ('Przedbórz','5');
INSERT INTO city(name,id_province) VALUES ('Przedecz','15');
INSERT INTO city(name,id_province) VALUES ('Przemków','1');
INSERT INTO city(name,id_province) VALUES ('Przemyśl','9');
INSERT INTO city(name,id_province) VALUES ('Przeworsk','9');
INSERT INTO city(name,id_province) VALUES ('Przysucha','7');
INSERT INTO city(name,id_province) VALUES ('Pszczyna','12');
INSERT INTO city(name,id_province) VALUES ('Pszów','12');
INSERT INTO city(name,id_province) VALUES ('Puck','11');
INSERT INTO city(name,id_province) VALUES ('Puławy','3');
INSERT INTO city(name,id_province) VALUES ('Pułtusk','7');
INSERT INTO city(name,id_province) VALUES ('Puszczykowo','15');
INSERT INTO city(name,id_province) VALUES ('Pyrzyce','16');
INSERT INTO city(name,id_province) VALUES ('Pyskowice','12');
INSERT INTO city(name,id_province) VALUES ('Pyzdry','15');
INSERT INTO city(name,id_province) VALUES ('Rabka','6');
INSERT INTO city(name,id_province) VALUES ('Raciąż','7');
INSERT INTO city(name,id_province) VALUES ('Racibórz','12');
INSERT INTO city(name,id_province) VALUES ('Radków','1');
INSERT INTO city(name,id_province) VALUES ('Radlin','12');
INSERT INTO city(name,id_province) VALUES ('Radom','7');
INSERT INTO city(name,id_province) VALUES ('Radomsko','5');
INSERT INTO city(name,id_province) VALUES ('Radomyśl Wielki','9');
INSERT INTO city(name,id_province) VALUES ('Radymno','9');
INSERT INTO city(name,id_province) VALUES ('Radziejów','2');
INSERT INTO city(name,id_province) VALUES ('Radzionków','12');
INSERT INTO city(name,id_province) VALUES ('Radzymin','7');
INSERT INTO city(name,id_province) VALUES ('Radzyń Chełmiński','2');
INSERT INTO city(name,id_province) VALUES ('Radzyń Podlaski','3');
INSERT INTO city(name,id_province) VALUES ('Rajgród','10');
INSERT INTO city(name,id_province) VALUES ('Rakoniewice','15');
INSERT INTO city(name,id_province) VALUES ('Raszków','15');
INSERT INTO city(name,id_province) VALUES ('Rawa Mazowiecka','5');
INSERT INTO city(name,id_province) VALUES ('Rawicz','15');
INSERT INTO city(name,id_province) VALUES ('Recz','16');
INSERT INTO city(name,id_province) VALUES ('Reda','11');
INSERT INTO city(name,id_province) VALUES ('Rejowiec Fabryczny','3');
INSERT INTO city(name,id_province) VALUES ('Resko','16');
INSERT INTO city(name,id_province) VALUES ('Reszel','14');
INSERT INTO city(name,id_province) VALUES ('Rogoźno','15');
INSERT INTO city(name,id_province) VALUES ('Ropczyce','9');
INSERT INTO city(name,id_province) VALUES ('Różan','7');
INSERT INTO city(name,id_province) VALUES ('Ruciane-Nida','14');
INSERT INTO city(name,id_province) VALUES ('Ruda Śląska','12');
INSERT INTO city(name,id_province) VALUES ('Rudnik nad Sanem','9');
INSERT INTO city(name,id_province) VALUES ('Rumia','11');
INSERT INTO city(name,id_province) VALUES ('Rybnik','12');
INSERT INTO city(name,id_province) VALUES ('Rychwał','15');
INSERT INTO city(name,id_province) VALUES ('Rydułtowy','12');
INSERT INTO city(name,id_province) VALUES ('Rydzyna','15');
INSERT INTO city(name,id_province) VALUES ('Ryki','3');
INSERT INTO city(name,id_province) VALUES ('Rymanów','9');
INSERT INTO city(name,id_province) VALUES ('Ryn','14');
INSERT INTO city(name,id_province) VALUES ('Rypin','2');
INSERT INTO city(name,id_province) VALUES ('Rzepin','4');
INSERT INTO city(name,id_province) VALUES ('Rzeszów','9');
INSERT INTO city(name,id_province) VALUES ('Sandomierz','13');
INSERT INTO city(name,id_province) VALUES ('Sanok','9');
INSERT INTO city(name,id_province) VALUES ('Sejny','10');
INSERT INTO city(name,id_province) VALUES ('Serock','7');
INSERT INTO city(name,id_province) VALUES ('Sędziszów','13');
INSERT INTO city(name,id_province) VALUES ('Sędziszów Małopolski','9');
INSERT INTO city(name,id_province) VALUES ('Sępopol','14');
INSERT INTO city(name,id_province) VALUES ('Sępólno Krajeńskie','2');
INSERT INTO city(name,id_province) VALUES ('Sianów','16');
INSERT INTO city(name,id_province) VALUES ('Siechnice','1');
INSERT INTO city(name,id_province) VALUES ('Siedlce','7');
INSERT INTO city(name,id_province) VALUES ('Siemianowice 12','12');
INSERT INTO city(name,id_province) VALUES ('Siemiatycze','10');
INSERT INTO city(name,id_province) VALUES ('Sieniawa','9');
INSERT INTO city(name,id_province) VALUES ('Sieradz','5');
INSERT INTO city(name,id_province) VALUES ('Sieraków','15');
INSERT INTO city(name,id_province) VALUES ('Sierpc','7');
INSERT INTO city(name,id_province) VALUES ('Siewierz','12');
INSERT INTO city(name,id_province) VALUES ('Skalbmierz','13');
INSERT INTO city(name,id_province) VALUES ('Skała','6');
INSERT INTO city(name,id_province) VALUES ('Skarszewy','11');
INSERT INTO city(name,id_province) VALUES ('Skaryszew','7');
INSERT INTO city(name,id_province) VALUES ('Skarżysko-Kamienna','13');
INSERT INTO city(name,id_province) VALUES ('Skawina','6');
INSERT INTO city(name,id_province) VALUES ('Skępe','2');
INSERT INTO city(name,id_province) VALUES ('Skierniewice','5');
INSERT INTO city(name,id_province) VALUES ('Skoczów','12');
INSERT INTO city(name,id_province) VALUES ('Skoki','15');
INSERT INTO city(name,id_province) VALUES ('Skórcz','11');
INSERT INTO city(name,id_province) VALUES ('Skwierzyna','4');
INSERT INTO city(name,id_province) VALUES ('Sława','4');
INSERT INTO city(name,id_province) VALUES ('Sławków','6');
INSERT INTO city(name,id_province) VALUES ('Sławno','16');
INSERT INTO city(name,id_province) VALUES ('Słomniki','6');
INSERT INTO city(name,id_province) VALUES ('Słubice','4');
INSERT INTO city(name,id_province) VALUES ('Słupca','15');
INSERT INTO city(name,id_province) VALUES ('Słupsk','11');
INSERT INTO city(name,id_province) VALUES ('Sobótka','1');
INSERT INTO city(name,id_province) VALUES ('Sochaczew','7');
INSERT INTO city(name,id_province) VALUES ('Sokołów Małopolski','9');
INSERT INTO city(name,id_province) VALUES ('Sokołów Podlaski','7');
INSERT INTO city(name,id_province) VALUES ('Sokółka','10');
INSERT INTO city(name,id_province) VALUES ('Solec Kujawski','2');
INSERT INTO city(name,id_province) VALUES ('Sompolno','15');
INSERT INTO city(name,id_province) VALUES ('Sopot','11');
INSERT INTO city(name,id_province) VALUES ('Sosnowiec','12');
INSERT INTO city(name,id_province) VALUES ('Sośnicowice','12');
INSERT INTO city(name,id_province) VALUES ('Stalowa Wola','9');
INSERT INTO city(name,id_province) VALUES ('Starachowice','13');
INSERT INTO city(name,id_province) VALUES ('Stargard Szczeciński','16');
INSERT INTO city(name,id_province) VALUES ('Starogard Gdański','11');
INSERT INTO city(name,id_province) VALUES ('Stary Sącz','6');
INSERT INTO city(name,id_province) VALUES ('Staszów','13');
INSERT INTO city(name,id_province) VALUES ('Stawiski','10');
INSERT INTO city(name,id_province) VALUES ('Stawiszyn','15');
INSERT INTO city(name,id_province) VALUES ('Stąporków','13');
INSERT INTO city(name,id_province) VALUES ('Stęszew','15');
INSERT INTO city(name,id_province) VALUES ('Stoczek Łukowski','3');
INSERT INTO city(name,id_province) VALUES ('Stronie 12','1');
INSERT INTO city(name,id_province) VALUES ('Strumień','12');
INSERT INTO city(name,id_province) VALUES ('Stryków','5');
INSERT INTO city(name,id_province) VALUES ('Strzegom','1');
INSERT INTO city(name,id_province) VALUES ('Strzelce Krajeńskie','4');
INSERT INTO city(name,id_province) VALUES ('Strzelce 8','8');
INSERT INTO city(name,id_province) VALUES ('Strzelin','1');
INSERT INTO city(name,id_province) VALUES ('Strzelno','2');
INSERT INTO city(name,id_province) VALUES ('Strzyżów','9');
INSERT INTO city(name,id_province) VALUES ('Sucha Beskidzka','6');
INSERT INTO city(name,id_province) VALUES ('Suchań','16');
INSERT INTO city(name,id_province) VALUES ('Suchedniów','13');
INSERT INTO city(name,id_province) VALUES ('Suchowola','10');
INSERT INTO city(name,id_province) VALUES ('Sulechów','4');
INSERT INTO city(name,id_province) VALUES ('Sulejów','5');
INSERT INTO city(name,id_province) VALUES ('Sulejówek','7');
INSERT INTO city(name,id_province) VALUES ('Sulęcin','4');
INSERT INTO city(name,id_province) VALUES ('Sulmierzyce','15');
INSERT INTO city(name,id_province) VALUES ('Sułkowice','6');
INSERT INTO city(name,id_province) VALUES ('Supraśl','10');
INSERT INTO city(name,id_province) VALUES ('Suraż','10');
INSERT INTO city(name,id_province) VALUES ('Susz','14');
INSERT INTO city(name,id_province) VALUES ('Suwałki','10');
INSERT INTO city(name,id_province) VALUES ('Swarzędz','15');
INSERT INTO city(name,id_province) VALUES ('Syców','1');
INSERT INTO city(name,id_province) VALUES ('Szadek','5');
INSERT INTO city(name,id_province) VALUES ('Szamocin','15');
INSERT INTO city(name,id_province) VALUES ('Szamotuły','15');
INSERT INTO city(name,id_province) VALUES ('Szczawnica','6');
INSERT INTO city(name,id_province) VALUES ('Szczawno Zdrój','1');
INSERT INTO city(name,id_province) VALUES ('Szczebrzeszyn','3');
INSERT INTO city(name,id_province) VALUES ('Szczecin','16');
INSERT INTO city(name,id_province) VALUES ('Szczecinek','16');
INSERT INTO city(name,id_province) VALUES ('Szczekociny','12');
INSERT INTO city(name,id_province) VALUES ('Szczuczyn','10');
INSERT INTO city(name,id_province) VALUES ('Szczyrk','12');
INSERT INTO city(name,id_province) VALUES ('Szczytna','1');
INSERT INTO city(name,id_province) VALUES ('Szczytno','14');
INSERT INTO city(name,id_province) VALUES ('Szklarska Poręba','1');
INSERT INTO city(name,id_province) VALUES ('Szlichtyngowa','4');
INSERT INTO city(name,id_province) VALUES ('Szprotawa','4');
INSERT INTO city(name,id_province) VALUES ('Sztum','11');
INSERT INTO city(name,id_province) VALUES ('Szubin','2');
INSERT INTO city(name,id_province) VALUES ('Szydłowiec','7');
INSERT INTO city(name,id_province) VALUES ('Ścinawa','1');
INSERT INTO city(name,id_province) VALUES ('Ślesin','15');
INSERT INTO city(name,id_province) VALUES ('Śmigiel','15');
INSERT INTO city(name,id_province) VALUES ('Śrem','15');
INSERT INTO city(name,id_province) VALUES ('Środa Śląska','1');
INSERT INTO city(name,id_province) VALUES ('Środa Wielkopolska','15');
INSERT INTO city(name,id_province) VALUES ('Świątniki Górne','6');
INSERT INTO city(name,id_province) VALUES ('Świdnica','1');
INSERT INTO city(name,id_province) VALUES ('Świdnik','3');
INSERT INTO city(name,id_province) VALUES ('Świdwin','16');
INSERT INTO city(name,id_province) VALUES ('Świebodzice','1');
INSERT INTO city(name,id_province) VALUES ('Świebodzin','4');
INSERT INTO city(name,id_province) VALUES ('Świecie','2');
INSERT INTO city(name,id_province) VALUES ('Świeradów Zdrój','1');
INSERT INTO city(name,id_province) VALUES ('Świerzawa','1');
INSERT INTO city(name,id_province) VALUES ('Świętochłowice','12');
INSERT INTO city(name,id_province) VALUES ('Świnoujście','16');
INSERT INTO city(name,id_province) VALUES ('Tarnobrzeg','9');
INSERT INTO city(name,id_province) VALUES ('Tarnogród','3');
INSERT INTO city(name,id_province) VALUES ('Tarnowskie Góry','12');
INSERT INTO city(name,id_province) VALUES ('Tarnów','6');
INSERT INTO city(name,id_province) VALUES ('Tczew','11');
INSERT INTO city(name,id_province) VALUES ('Terespol','3');
INSERT INTO city(name,id_province) VALUES ('Tłuszcz','7');
INSERT INTO city(name,id_province) VALUES ('Tolkmicko','14');
INSERT INTO city(name,id_province) VALUES ('Tomaszów Lubelski','3');
INSERT INTO city(name,id_province) VALUES ('Tomaszów Mazowiecki','5');
INSERT INTO city(name,id_province) VALUES ('Toruń','2');
INSERT INTO city(name,id_province) VALUES ('Torzym','4');
INSERT INTO city(name,id_province) VALUES ('Toszek','12');
INSERT INTO city(name,id_province) VALUES ('Trzcianka','15');
INSERT INTO city(name,id_province) VALUES ('Trzciel','4');
INSERT INTO city(name,id_province) VALUES ('Trzcińsko Zdrój','16');
INSERT INTO city(name,id_province) VALUES ('Trzebiatów','16');
INSERT INTO city(name,id_province) VALUES ('Trzebinia','6');
INSERT INTO city(name,id_province) VALUES ('Trzebnica','1');
INSERT INTO city(name,id_province) VALUES ('Trzemeszno','15');
INSERT INTO city(name,id_province) VALUES ('Tuchola','2');
INSERT INTO city(name,id_province) VALUES ('Tuchów','6');
INSERT INTO city(name,id_province) VALUES ('Tuczno','16');
INSERT INTO city(name,id_province) VALUES ('Tuliszków','15');
INSERT INTO city(name,id_province) VALUES ('Turek','15');
INSERT INTO city(name,id_province) VALUES ('Tuszyn','5');
INSERT INTO city(name,id_province) VALUES ('Twardogóra','1');
INSERT INTO city(name,id_province) VALUES ('Tychy','12');
INSERT INTO city(name,id_province) VALUES ('Tyczyn','9');
INSERT INTO city(name,id_province) VALUES ('Tykocin','10');
INSERT INTO city(name,id_province) VALUES ('Ujazd','8');
INSERT INTO city(name,id_province) VALUES ('Ujście','15');
INSERT INTO city(name,id_province) VALUES ('Ulanów','9');
INSERT INTO city(name,id_province) VALUES ('Uniejów','5');
INSERT INTO city(name,id_province) VALUES ('Ustka','11');
INSERT INTO city(name,id_province) VALUES ('Ustroń','12');
INSERT INTO city(name,id_province) VALUES ('Ustrzyki Dolne','9');
INSERT INTO city(name,id_province) VALUES ('Wadowice','6');
INSERT INTO city(name,id_province) VALUES ('Wałbrzych','1');
INSERT INTO city(name,id_province) VALUES ('Wałcz','16');
INSERT INTO city(name,id_province) VALUES ('Warka','7');
INSERT INTO city(name,id_province) VALUES ('Warszawa','7');
INSERT INTO city(name,id_province) VALUES ('Warta','5');
INSERT INTO city(name,id_province) VALUES ('Wasilków','10');
INSERT INTO city(name,id_province) VALUES ('Wąbrzeźno','2');
INSERT INTO city(name,id_province) VALUES ('Wąchock','13');
INSERT INTO city(name,id_province) VALUES ('Wągrowiec','15');
INSERT INTO city(name,id_province) VALUES ('Wąsosz','1');
INSERT INTO city(name,id_province) VALUES ('Wejherowo','11');
INSERT INTO city(name,id_province) VALUES ('Wesoła','7');
INSERT INTO city(name,id_province) VALUES ('Węgliniec','1');
INSERT INTO city(name,id_province) VALUES ('Węgorzewo','14');
INSERT INTO city(name,id_province) VALUES ('Węgorzyno','16');
INSERT INTO city(name,id_province) VALUES ('Węgrów','7');
INSERT INTO city(name,id_province) VALUES ('Wiązów','1');
INSERT INTO city(name,id_province) VALUES ('Wieleń','15');
INSERT INTO city(name,id_province) VALUES ('Wielichowo','15');
INSERT INTO city(name,id_province) VALUES ('Wieliczka','6');
INSERT INTO city(name,id_province) VALUES ('Wieluń','5');
INSERT INTO city(name,id_province) VALUES ('Wieruszów','5');
INSERT INTO city(name,id_province) VALUES ('Więcbork','2');
INSERT INTO city(name,id_province) VALUES ('Wilamowice','12');
INSERT INTO city(name,id_province) VALUES ('Wisła','12');
INSERT INTO city(name,id_province) VALUES ('Witkowo','15');
INSERT INTO city(name,id_province) VALUES ('Witnica','4');
INSERT INTO city(name,id_province) VALUES ('Wleń','1');
INSERT INTO city(name,id_province) VALUES ('Władysławowo','11');
INSERT INTO city(name,id_province) VALUES ('Włocławek','2');
INSERT INTO city(name,id_province) VALUES ('Włodawa','3');
INSERT INTO city(name,id_province) VALUES ('Włoszczowa','13');
INSERT INTO city(name,id_province) VALUES ('Wodzisław Śląski','12');
INSERT INTO city(name,id_province) VALUES ('Wojcieszów','1');
INSERT INTO city(name,id_province) VALUES ('Wojkowice','12');
INSERT INTO city(name,id_province) VALUES ('Wolbrom','6');
INSERT INTO city(name,id_province) VALUES ('Wolin','16');
INSERT INTO city(name,id_province) VALUES ('Wolsztyn','15');
INSERT INTO city(name,id_province) VALUES ('Wołczyn','8');
INSERT INTO city(name,id_province) VALUES ('Wołomin','7');
INSERT INTO city(name,id_province) VALUES ('Wołów','1');
INSERT INTO city(name,id_province) VALUES ('Woźniki','12');
INSERT INTO city(name,id_province) VALUES ('Wrocław','1');
INSERT INTO city(name,id_province) VALUES ('Wronki','15');
INSERT INTO city(name,id_province) VALUES ('Września','15');
INSERT INTO city(name,id_province) VALUES ('Wschowa','4');
INSERT INTO city(name,id_province) VALUES ('Wyrzysk','15');
INSERT INTO city(name,id_province) VALUES ('Wysoka','15');
INSERT INTO city(name,id_province) VALUES ('Wysokie 7','10');
INSERT INTO city(name,id_province) VALUES ('Wyszków','7');
INSERT INTO city(name,id_province) VALUES ('Wyszogród','7');
INSERT INTO city(name,id_province) VALUES ('Wyśmierzyce','7');
INSERT INTO city(name,id_province) VALUES ('Zabłudów','10');
INSERT INTO city(name,id_province) VALUES ('Zabrze','12');
INSERT INTO city(name,id_province) VALUES ('Zagórów','15');
INSERT INTO city(name,id_province) VALUES ('Zagórz','9');
INSERT INTO city(name,id_province) VALUES ('Zakopane','6');
INSERT INTO city(name,id_province) VALUES ('Zakroczym','7');
INSERT INTO city(name,id_province) VALUES ('Zalewo','14');
INSERT INTO city(name,id_province) VALUES ('Zambrów','10');
INSERT INTO city(name,id_province) VALUES ('Zamość','3');
INSERT INTO city(name,id_province) VALUES ('Zator','6');
INSERT INTO city(name,id_province) VALUES ('Zawadzkie','8');
INSERT INTO city(name,id_province) VALUES ('Zawichost','13');
INSERT INTO city(name,id_province) VALUES ('Zawidów','1');
INSERT INTO city(name,id_province) VALUES ('Zawiercie','12');
INSERT INTO city(name,id_province) VALUES ('Ząbki','7');
INSERT INTO city(name,id_province) VALUES ('Ząbkowice 12','1');
INSERT INTO city(name,id_province) VALUES ('Zbąszynek','4');
INSERT INTO city(name,id_province) VALUES ('Zbąszyń','15');
INSERT INTO city(name,id_province) VALUES ('Zduny','15');
INSERT INTO city(name,id_province) VALUES ('Zduńska Wola','5');
INSERT INTO city(name,id_province) VALUES ('Zdzieszowice','8');
INSERT INTO city(name,id_province) VALUES ('Zelów','5');
INSERT INTO city(name,id_province) VALUES ('Zgierz','5');
INSERT INTO city(name,id_province) VALUES ('Zgorzelec','1');
INSERT INTO city(name,id_province) VALUES ('Zielona Góra','4');
INSERT INTO city(name,id_province) VALUES ('Zielonka','7');
INSERT INTO city(name,id_province) VALUES ('Ziębice','1');
INSERT INTO city(name,id_province) VALUES ('Złocieniec','16');
INSERT INTO city(name,id_province) VALUES ('Złoczew','5');
INSERT INTO city(name,id_province) VALUES ('Złotoryja','1');
INSERT INTO city(name,id_province) VALUES ('Złotów','15');
INSERT INTO city(name,id_province) VALUES ('Złoty Stok','1');
INSERT INTO city(name,id_province) VALUES ('Zwierzyniec','3');
INSERT INTO city(name,id_province) VALUES ('Zwoleń','7');
INSERT INTO city(name,id_province) VALUES ('Żabno','6');
INSERT INTO city(name,id_province) VALUES ('Żagań','4');
INSERT INTO city(name,id_province) VALUES ('Żarki','12');
INSERT INTO city(name,id_province) VALUES ('Żarów','1');
INSERT INTO city(name,id_province) VALUES ('Żary','4');
INSERT INTO city(name,id_province) VALUES ('Żelechów','7');
INSERT INTO city(name,id_province) VALUES ('Żerków','15');
INSERT INTO city(name,id_province) VALUES ('Żmigród','1');
INSERT INTO city(name,id_province) VALUES ('Żnin','2');
INSERT INTO city(name,id_province) VALUES ('Żory','12');
INSERT INTO city(name,id_province) VALUES ('Żukowo','11');
INSERT INTO city(name,id_province) VALUES ('Żuromin','7');
INSERT INTO city(name,id_province) VALUES ('Żychlin','5');
INSERT INTO city(name,id_province) VALUES ('Żyrardów','7');
INSERT INTO city(name,id_province) VALUES ('Żywiec','12');
UPDATE city AS c SET c.id_country = '135' WHERE id > 0